name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    failOnThreshold: critical  # Optional: moderate (default), low, high, critical
    Type: kubernetes # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    variableGroupName: ffc-doc-alerting-env-var
    pr_params:
      container.notifyApiKey: $(pr_notifyApiKey)
      container.devTeamEmails: $(pr_devTeamEmails)
      container.dwhEmails: $(pr_dwhEmails)
      container.sendAlerts: $(pr_sendAlerts)
    snd2_params:
      container.notifyApiKey: $(snd2_notifyApiKey)
      container.devTeamEmails: $(snd2_devTeamEmails)
      container.dwhEmails: $(snd2_dwhEmails)
      container.sendAlerts: $(snd2_sendAlerts)
    dev_params:
      container.notifyApiKey: $(dev_notifyApiKey)
      container.devTeamEmails: $(dev_devTeamEmails)
      container.dwhEmails: $(dev_dwhEmails)
      container.sendAlerts: $(dev_sendAlerts)
    test_params:
      container.notifyApiKey: $(test_notifyApiKey)
      container.devTeamEmails: $(test_devTeamEmails)
      container.dwhEmails: $(test_dwhEmails)
      container.sendAlerts: $(test_sendAlerts)
    pre_params:
      container.notifyApiKey: $(pre_notifyApiKey)
      container.devTeamEmails: $(pre_devTeamEmails)
      container.dwhEmails: $(pre_dwhEmails)
      container.sendAlerts: $(pre_sendAlerts)
    prd_params:
      container.notifyApiKey: $(prd_notifyApiKey)
      container.devTeamEmails: $(prd_devTeamEmails)
      container.dwhEmails: $(prd_dwhEmails)
      container.sendAlerts: $(prd_sendAlerts)
