services:
  ffc-doc-alerting:
    build:
      context: .
      target: production
    image: ffc-doc-alerting
    container_name: ffc-doc-alerting
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-doc-alerting-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      ALERT_TOPIC_ADDRESS: ${ALERT_TOPIC_ADDRESS:-ffc-doc-alerting}${MESSAGE_QUEUE_SUFFIX}
      ALERT_SUBSCRIPTION_ADDRESS: ${ALERT_SUBSCRIPTION_ADDRESS:-ffc-doc-alert}${MESSAGE_QUEUE_SUFFIX}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      DEV_TEAM_EMAILS: ${DEV_TEAM_EMAILS}
      DWH_EMAILS: ${DWH_EMAILS}
      FFC_ENVIRONMENT: local
