# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-doc-alerting:
    build:
      target: development
    image: ffc-doc-alerting-development
    container_name: ffc-doc-alerting-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NOTIFY_API_KEY: A_TEST_KEY
      DEV_TEAM_EMAILS: testDev@test.com

