# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-doc-alerting:
    build:
      target: development
    image: ffc-doc-alerting-development
    container_name: ffc-doc-alerting-development
    ports:
      - "9429:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-responses-azurite:10000/devstoreaccount1;
    depends_on:
      - ffc-pay-responses-azurite

volumes:
  azurite_data: