{{- include "ffc-helm-library.container-config-map" (list . "ffc-doc-alerting.config-map") -}}
{{- define "ffc-doc-alerting.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  ALERT_TOPIC_ADDRESS: {{ .Values.container.alertTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  ALERT_TOPIC_ADDRESS: {{ quote .Values.container.alertTopicAddress }}
  {{- end }}
  ALERT_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.alertSubscriptionAddress }}
  {{- if .Values.container.devTeamEmails }}
  DEV_TEAM_EMAILS: {{ quote .Values.container.devTeamEmails }}
  {{- end }}
  FFC_ENVIRONMENT: {{ quote .Values.environmentCode }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
  SEND_ALERTS: {{ quote .Values.container.sendAlerts }}
{{- end -}}
