const {
  PROCESSING_SUBSCRIPTION_FAILED: PROCESSING_SUBSCRIPTION_FAILED_EVENT,
  SUBMIT_SUBSCRIPTION_FAILED: SUBMIT_SUBSCRIPTION_FAILED_EVENT,
  RETURN_SUBSCRIPTION_FAILED: RETURN_SUBSCRIPTION_FAILED_EVENT,
  ETL_PROCESS_ERROR: ETL_PROCESS_ERROR_EVENT,
  PUBLISH_ERROR: PUBLISH_ERROR_EVENT,
  ZERO_VALUE_STATEMENT: ZERO_VALUE_STATEMENT_EVENT,
  DATA_PROCESSING_ERROR: DATA_PROCESSING_ERROR_EVENT,
  DATA_PUBLISHING_ERROR: DATA_PUBLISHING_ERROR_EVENT,
  DUPLICATE_RECORD
} = require('./events')

const {
  PROCESSING_SUBSCRIPTION_FAILED: PROCESSING_SUBSCRIPTION_FAILED_TEMPLATE,
  SUBMIT_SUBSCRIPTION_FAILED: SUBMIT_SUBSCRIPTION_FAILED_TEMPLATE,
  RETURN_SUBSCRIPTION_FAILED: RETURN_SUBSCRIPTION_FAILED_TEMPLATE,
  ETL_PROCESS_ERROR: ETL_PROCESS_ERROR_TEMPLATE,
  PUBLISH_ERROR: PUBLISH_ERROR_TEMPLATE,
  ZERO_VALUE_STATEMENT: ZERO_VALUE_STATEMENT_TEMPLATE,
  DATA_PROCESSING_ERROR: DATA_PROCESSING_ERROR_TEMPLATE,
  DATA_PUBLISHING_ERROR: DATA_PUBLISHING_ERROR_TEMPLATE,
  DUPLICATE_RECORD: DUPLICATE_RECORD_TEMPLATE
} = require('./templates')

module.exports = {
  [PROCESSING_SUBSCRIPTION_FAILED_EVENT]: PROCESSING_SUBSCRIPTION_FAILED_TEMPLATE,
  [SUBMIT_SUBSCRIPTION_FAILED_EVENT]: SUBMIT_SUBSCRIPTION_FAILED_TEMPLATE,
  [RETURN_SUBSCRIPTION_FAILED_EVENT]: RETURN_SUBSCRIPTION_FAILED_TEMPLATE,
  [ETL_PROCESS_ERROR_EVENT]: ETL_PROCESS_ERROR_TEMPLATE,
  [PUBLISH_ERROR_EVENT]: PUBLISH_ERROR_TEMPLATE,
  [ZERO_VALUE_STATEMENT_EVENT]: ZERO_VALUE_STATEMENT_TEMPLATE,
  [DATA_PROCESSING_ERROR_EVENT]: DATA_PROCESSING_ERROR_TEMPLATE,
  [DATA_PUBLISHING_ERROR_EVENT]: DATA_PUBLISHING_ERROR_TEMPLATE,
  [DUPLICATE_RECORD]: DUPLICATE_RECORD_TEMPLATE
}
