environment: production
environmentCode:
name: ffc-doc-alerting
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-alerting

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-doc-alerting-config-map

containerSecret:
  name: ffc-doc-alerting-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  messageQueueHost: namespace.servicebus.windows.net
  alertTopicAddress: ffc-doc-alerting
  alertSubscriptionAddress: ffc-doc-alert
  notifyApiKey:
  devTeamEmails:
  sendAlerts: true

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
